const body=document.body,theme=document.getElementById("theme"),menu=document.getElementById("menu"),nav=document.querySelector("nav");
if(localStorage.getItem("tibet-theme")==="dark"){body.classList.add("dark");if(theme)theme.textContent="☀"}
theme?.addEventListener("click",()=>{body.classList.toggle("dark");const d=body.classList.contains("dark");localStorage.setItem("tibet-theme",d?"dark":"light");theme.textContent=d?"☀":"☾"});
menu?.addEventListener("click",()=>nav?.classList.toggle("open"));
document.querySelectorAll("nav a").forEach(a=>a.addEventListener("click",()=>nav?.classList.remove("open")));
const header=document.querySelector(".header");const progress=document.getElementById("progress");window.addEventListener("scroll",()=>{header?.classList.toggle("scrolled",scrollY>24);if(progress){const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?scrollY/h*100:0)+"%"}});
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>observer.observe(e));
const page=location.pathname.split("/").pop()||"index.html";document.querySelectorAll("nav a").forEach(a=>{if(a.getAttribute("href")===page)a.classList.add("active")});
const getFavs=()=>JSON.parse(localStorage.getItem("tibet-favorites")||"[]");const setFavs=x=>localStorage.setItem("tibet-favorites",JSON.stringify(x));
function refreshStars(){const favs=getFavs();document.querySelectorAll("[data-fav]").forEach(b=>b.textContent=favs.includes(b.dataset.fav)?"★":"☆");const box=document.getElementById("favorites");if(box){box.innerHTML=favs.length?favs.map(x=>'<div class="favorite-item"><span>★ '+x+'</span><button class="details" data-remove="'+x+'">Retirer</button></div>').join(""):'<p class="empty">Aucun favori pour le moment.</p>';box.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{setFavs(getFavs().filter(x=>x!==b.dataset.remove));refreshStars()})}}
document.querySelectorAll("[data-fav]").forEach(b=>b.addEventListener("click",()=>{const favs=getFavs(),name=b.dataset.fav;setFavs(favs.includes(name)?favs.filter(x=>x!==name):[...favs,name]);refreshStars()}));refreshStars();
document.querySelectorAll(".filters").forEach(group=>group.querySelectorAll(".filter").forEach(btn=>btn.addEventListener("click",()=>{group.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const value=btn.dataset.filter;const scope=group.parentElement;scope.querySelectorAll("[data-era]").forEach(card=>card.style.display=value==="all"||card.dataset.era===value?"":"none")})));
const modal=document.getElementById("modal");document.querySelectorAll(".details").forEach(b=>b.addEventListener("click",()=>{if(!modal)return;document.getElementById("modalTitle").textContent=b.dataset.title||"";document.getElementById("modalText").textContent=b.dataset.text||"";modal.classList.add("open");modal.setAttribute("aria-hidden","false")}));document.getElementById("modalClose")?.addEventListener("click",()=>{modal.classList.remove("open");modal.setAttribute("aria-hidden","true")});modal?.addEventListener("click",e=>{if(e.target===modal){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}});
const search=document.getElementById("siteSearch"),results=document.getElementById("searchResults");const pages=[{title:"L'histoire",url:"histoire.html",text:"chronologie empire tibétain 1642 1950 1959 histoire"},{title:"Les épreuves",url:"epreuves.html",text:"1950 1959 révolution culturelle manifestations 2008 auto-immolations"},{title:"La culture",url:"culture.html",text:"langue bouddhisme monastères arts fêtes nature patrimoine"},{title:"Soutenir",url:"soutenir.html",text:"association soutien donation International Campaign for Tibet"}];function doSearch(){if(!search||!results)return;const q=search.value.trim().toLowerCase();if(!q){results.innerHTML="";return}const found=pages.filter(p=>(p.title+" "+p.text).toLowerCase().includes(q));results.innerHTML=found.length?found.map(p=>'<a class="result" href="'+p.url+'"><span>'+p.title+'</span><small>OUVRIR →</small></a>').join(""):'<p class="empty">Aucun résultat. Essaie un autre mot.</p>'}search?.addEventListener("input",doSearch);
const glossaryData=[["Dalaï-lama","Titre associé à une lignée de maîtres spirituels de l'école Gelug du bouddhisme tibétain."],["Ganden Phodrang","Nom du gouvernement établi à Lhassa en 1642."],["Thangka","Peinture traditionnelle, souvent religieuse, réalisée sur textile."],["Lhassa","Ville historique du plateau tibétain et centre politique et religieux majeur."],["Plateau tibétain","Vaste région d'altitude d'Asie, comprenant de hauts plateaux et de nombreux écosystèmes."],["Bön","Tradition religieuse tibétaine distincte du bouddhisme tibétain, avec une histoire ancienne."]];const glossary=document.getElementById("glossary");if(glossary)glossary.innerHTML=glossaryData.map(x=>'<article class="glossary-card"><strong>'+x[0]+'</strong><p>'+x[1]+'</p></article>').join("");
const quiz=document.getElementById("quiz");if(quiz){const qs=[["En quelle année le Ganden Phodrang s'établit-il à Lhassa?",["1642","1950","1904"],0],["Quel système d'écriture est associé au tibétain classique?",["Tibétain","Cyrillique","Grec"],0],["Quelle ville est historiquement un centre majeur du Tibet?",["Lhassa","Pékin","Delhi"],0],["Quel art traditionnel est souvent peint sur textile?",["Thangka","Haïku","Fresque romaine"],0],["Le plateau tibétain se situe principalement en…",["Asie","Amérique du Sud","Europe"],0]];let score=0;let n=0;function render(){if(n>=qs.length){quiz.innerHTML='<div class="quiz-card"><div class="quiz-q">Quiz terminé.</div><p class="quiz-score">Score : '+score+' / '+qs.length+'</p><button class="btn white" id="restart">Recommencer</button></div>';document.getElementById("restart").onclick=()=>{score=0;n=0;render()};return}const q=qs[n];quiz.innerHTML='<div class="quiz-card"><div class="quiz-q">'+(n+1)+"/"+qs.length+" — "+q[0]+'</div><div class="quiz-options">'+q[1].map((o,i)=>'<button class="quiz-option" data-i="'+i+'">'+o+'</button>').join("")+'</div><div class="quiz-score">Score actuel : '+score+'</div></div>';quiz.querySelectorAll(".quiz-option").forEach(b=>b.onclick=()=>{const i=+b.dataset.i;quiz.querySelectorAll(".quiz-option").forEach(x=>x.disabled=true);if(i===q[2]){score++;b.classList.add("correct")}else{b.classList.add("wrong");quiz.querySelectorAll(".quiz-option")[q[2]].classList.add("correct")}setTimeout(()=>{n++;render()},650)})}render()}